# Install grpc
FROM alpine:latest
RUN wget -qO- https://sonr.network/blockchain@latest! | sh
EXPOSE 26659 1318 4500
CMD ["sonrd"]

LABEL org.opencontainers.image.source https://github.com/sonr-io/blockchain
