version: "3"

includes:
  vue:
    taskfile: ./vue/Taskfile.yaml
    dir: ./vue

tasks:
  build:
    summary: Build the project for production without release mode
    cmds:
      - starport chain build
    silent: true

  buf:
    summary: Build and Publish proto to buf.build
    cmds:
      - buf build
      - buf push
    silent: true
    dir: ./proto

  gen:
    summary: Generates protobuf, openapi, and vue stores
    cmds:
      - starport generate openapi
      - starport generate proto-go
      - go mod tidy
    silent: true

  serve:
    summary: Serve the blockchain using starport
    cmds:
      - starport chain serve --reset-once
    silent: true

  start:
    summary: Start a locally built blockchain daemon
    deps: [build]
    cmds:
      - rm -rf ~/.sonr
      - sonrd init my-node --chain-id sonr
      - sonrd keys add --keyring-backend test alice --home ~/.sonr
      - sonrd add-genesis-account $(sonrd keys show alice -a) 1000000000000000stake,1000000000000snr
      - sonrd gentx alice 1000000000000000stake --chain-id sonr
      - sonrd collect-gentxs
      - sonrd start

  clean:
    summary: Clean the project
    cmds:
      - rm -rf dist
      - rm -rf release
      - go mod tidy
