version: '3'

tasks:
  build:
    cmds:
      - echo "Exporting Sonr Highway Dashboard Frontend"
      - yarn install && yarn export

  serve:
    cmds:
      - echo "Running Sonr Highway Node"
      - go run highway.go

